import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const popSans = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
   weight :["100","200","300", "400","500","600","700","900"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${popSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
