import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";

const popSans = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
   weight :["100","200","300", "400","500","600","700","900"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${popSans.variable} h-full antialiased`}
    >
      <body className="flex flex-row bg-sky-200">
        <header className="fixed left-0 top-0 h-screen w-64 p-4 bg-violet-100">
          <Sidebar/>
        </header>
        <main className="ml-64 min-h-screen w-[calc(100%-16rem)] p-4 bg-orange-100 overflow-x-hidden">{children}</main>
        </body>
    </html>
  );
}
